import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Estilo.module.css";
import Contexto from "@/Context/contexto.js";
import React, { useState } from "react";
import Apresentacao from "./apresentacao"
// import EscreverTexto from "./escreverTexto";
import EscreverTexto from "./escreverTexto";
 


 

export default function Home() {

  const [paginaAtual, setPaginaAtual] =useState("nova nota");
  const [ListaBlocoNotas, setListaBlocoNotas] = useState([])
  const [editarConteudo, setEditarConteudo] = useState(true)
  const [blocoNotas, setBlocoNotas] = useState([null, null, 0])
  const [titulo, setTitulo] = useState("")
  const [texto, setTexto] = useState("")
  const [indexNotaAtual, setIndexNotaAtual] = useState(0)
  const [fechar, setFechar] =useState(true)
  const [menuMobile, setMenuMobile] = useState(false)
  
  





  function Atual() {

    if(paginaAtual == "nova nota"){
   return(
   <>
   <Apresentacao  />
   </>
        
   )
    } 
    else if(paginaAtual == "escrever texto" && ListaBlocoNotas != false){

   return(
   <>
   
   <EscreverTexto  />
              
   </>
            
       )
     
     }
   
     
     
   }
   




   function Overlay() {
    setMenuMobile(false)
    setFechar(true) 
    
    }
    






function Novoconteudo() {
  setIndexNotaAtual(ListaBlocoNotas.length)
setPaginaAtual("escrever texto")
 setBlocoNotas([null, null, ListaBlocoNotas.length])

 indexNotaAtual
setEditarConteudo(true)

setListaBlocoNotas(prevNotas => [
  ...prevNotas,
  {
  titulo: "texto sem titulo",
  texto: "" }
]);
}







function AbrirMenuMobile() {
 setMenuMobile(true)
  setFechar(true)

  }



function Fechar(params) {
setFechar(false)
setMenuMobile(false)
}








  return (
    <>
      <Head>
        <title>Bloco de notas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imagens/pencil-square.png" />
      </Head>

      <main className={`${styles.main_container} `}>

<div>
{menuMobile && (
  <div  className={`${styles.btn_fechar}`} onClick={Fechar} >
<img src="/imagens/x-circle.svg" alt=""  />
</div>


)
}



      
<div   className={`${styles.btn_abrir_menu}`}        id="meu-menu" onClick={AbrirMenuMobile} >
<img src="imagens/list.svg" alt="" />
</div> 
</div> 






<div   className={`${styles.grid_contaner} `}       > 


  
<div         
 className={`${styles.left_side_history}  ${menuMobile == true ? styles.abrir_menu : ""}                `}               >
  
  
      


<div  className={`${styles.new_chat} ${menuMobile == true ? styles.visibilidade : styles.visibilidade_none}  `}   id="new_chat"   onClick={Novoconteudo}  >
<h2  className={`${menuMobile == true ? styles.visibilidade : styles.visibilidade_none}  `}>
  <img src="imagens/mais.png"  alt="" width={20}/>New chat</h2>
</div> 
 




<div className={`${styles.container_titulos} ${menuMobile == true ? styles.visibilidade : styles.visibilidade_none}`}  id="container_titulos"  ></div>




{ListaBlocoNotas.map(({titulo,texto}, index ) => (
<h2 key={index}  className={`${styles.titulo_nota}  ${menuMobile == true ? styles.visibilidade : styles.visibilidade_none }`}  onClick={()=>{
setPaginaAtual("escrever texto")
setEditarConteudo(false)
setBlocoNotas([titulo, texto, index])
setIndexNotaAtual(index)
}}>{titulo}</h2>
    
   )) 
  }

</div> 



<div    className={`${styles.container_texto} ${menuMobile == true ? styles.visibilidade : ""}`}    >
<Contexto.Provider value={{setIndexNotaAtual, indexNotaAtual, ListaBlocoNotas, setListaBlocoNotas, titulo, setTitulo, texto, setTexto, blocoNotas, setBlocoNotas, paginaAtual, setPaginaAtual,  setListaBlocoNotas, editarConteudo, setEditarConteudo} } >
<Atual/>
</Contexto.Provider>
 

</div>   <div id="overlay_menu"    className={`${styles.overlay_menu}`}     onClick={Overlay}             ></div>

</div>
</main>




    </>
  );
}
